Zeus es el dios supremo de la antigua Grecia, conocido como el “Padre de dioses y hombres” y soberano indiscutible del monte Olimpo. Se le imagina como un hombre de imponente porte, de rasgos maduros y rostro enmarcado por una espesa barba rizada que acentúa su aire majestuoso. Su presencia evoca tanto la tranquilidad de un cielo despejado como la furia de una tormenta embravecida, pues en sus manos reside el poder de convocar truenos, relámpagos, vientos y lluvias. Desde lo alto de su palacio celestial, gobierna con autoridad y equilibra el destino de dioses y mortales por igual.

Zeus reina sobre el firmamento y, tras derrotar a los Titanes, se alzó con el dominio del cielo mientras sus hermanos recibían el mar y el inframundo. Controla los fenómenos meteorológicos: con un gesto suyo nacen las nubes cargadas de lluvia, el estruendo del trueno y el fulgor del rayo. Como guardián de la hospitalidad y los juramentos, vela también por el respeto a la palabra dada, castigando a quien traicione un pacto o deshonre a un huésped. Sus atributos más reconocibles son el rayo —forjado por los Cíclopes—, el cetro real que empuña con autoridad, el escudo llamado égida y el majestuoso águila que lo simboliza y acompaña en sus vigilias desde el cielo.

En el plano de la personalidad, Zeus combina la sabiduría y la justicia con un temperamento pasional. Es considerado un juez benévolo cuando se celebra con orden y respeto, pero implacable ante la injusticia, capaz de desencadenar tormentas devastadoras. Fuera de sus funciones divinas, disfruta de la camaradería y el buen humor, y no rehúye el festín ni la música en compañía de los otros dioses. No obstante, su naturaleza amorosa y curiosa le llevó a transformarse en múltiples formas —cisne, toro, cuclillo— para cortejar tanto a diosas como a mortales, lo que le generó continuos roces con su esposa Hera.

El nombre griego Ζεύς (Zeús) tiene su origen en la raíz proto‑indoeuropea dyeu‑, que alude a la luminosidad del cielo. En las inscripciones micénicas en lineal B aparece como di‑we o di‑wo, y su equivalente romano, Júpiter, procede de la misma raíz unida a la palabra pater (padre), formando Dyeu‑pater, “padre del cielo”.

Zeus fue el más joven de los seis hijos de Crono y Rea. Su padre, temeroso de una profecía que anunciaba su derrocamiento, se tragó a cada uno de sus hijos al nacer. Para salvar a Zeus, Rea engañó a Crono entregándole una piedra envuelta en pañales y ocultó al niño en una cueva de Creta, donde lo criaron la diosa Gea, la cabra Amaltea y las ninfas conocidas como Curetes. Cuando alcanzó la madurez, Zeus forzó a Crono a devolver a sus hermanos, y junto a ellos libró la gran contienda contra los Titanes. Tras diez años de lucha, los Olímpicos, con la ayuda decisiva de los Cíclopes, derrotaron a los ancestros de la humanidad y los confinaron en el Tártaro.

Con la victoria asegurada, Zeus estableció el nuevo orden del universo al repartírsele el cielo, mientras Poseidón se hizo señor de los océanos y Hades del reino subterráneo. Desde entonces, su reinado se consolidó enfrentando y sometiendo a toda revuelta divina: aplastó a los gigantes que amenazaron el mundo y venció a Typhon, el monstruo enviado por la Tierra para destruir el Olimpo. A partir de entonces, su figura se erigió como garante de la justicia y el mantenimiento del equilibrio cósmico, y en cada rincón de Grecia se le rindió culto como protector de las ciudades, los hogares y la moral de los hombres.